### ISSUE TITLE
GNU General Public License, v2.0 Violation

### ISSUE THREAD

**Issue by cfunseth** [sualfred/skin.embuary#17]
In looking through the history of this project, it looks as though your current CC by-nc-nd 4.0 license is in violation of the original source code's GPL v2.0 license.  

The original commit can be referenced here: https://github.com/sualfred/skin.embuary/commit/dc2c45a0b549c56f880ba6a2a3e58564f9fdd0d1

I believe this is the applicable language form [GPL v2.0:](https://www.gnu.org/licenses/gpl-2.0)
> 6. Each time you redistribute the Program (or any work based on the Program), the recipient automatically receives a license from the original licensor to copy, distribute or modify the Program subject to these terms and conditions. You may not impose any further restrictions on the recipients' exercise of the rights granted herein. You are not responsible for enforcing compliance by third parties to this License.

Just wanted to make you aware of this to hopefully avoid future issues.

**Comment by sualfred** [comment]
The old license file was just a leftover of my working directory and were parts of the Estuary skin which I used a "files-skelleton".  If you look closely you will see that it's the one of Estuary.
Each code line in this skin was replaced and written from scratch by myself. I also even made my own Python scripts so this skin and tools are based 99% of my work. The rest 1% are modules that are freely availlable in the Kodi repo.

The reason why I used CC by-nc-nd 4.0 is just the fact that I was dealing with wizard builders and box pirates that shipped my skin with their illegal crapware. The problem is, that my name etc. is always mentioned somwhere in the code and this unwanted releases. So it's kind of self protection.  I can nothing do against them but at the end of the story I stated clearly that I have no relationship to these law breakers. A very important point in case of a sue/law situation.

Personally I prefer to "live and let die". Everyone can fork my skin for personal use if you give proper credits. I just don't like if someone is forking it, renaming it, and just changing a bunch of lines just to release it again. That's not how "respect" works :) 

So if you have any plans do to you own mod and you have nothing to do with these banned addons that are destroying the Kodi community -> Do it. Other point of views are always an inspiration.
