### ISSUE TITLE
Problem with auto-refresh widget on new content

### ISSUE THREAD

**Issue by angus2064** [sualfred/skin.embuary#29]
Hello !

Since the last update ,I noticed a problem with the auto-refresh of the widgets (I use Embuary+Embycon). 
Before that ,when I added a new content to my Emby server ,the movie/tv show appear in the "added recently" widget on my homepage in approximately 10 or 15 seconds but now I noticed than the widget never refresh automatically on new content. After waiting some minutes I decided to go to the movie HUB (or TVShow) and here ,the new content added are showed correctly but just because the widget are refresh when the HUBs are opened ,if I stay here and then I add a new content I got the same problem than on the homepage.  
So the widgets are not refresh correctly on new content added but works correctly if I force the refresh when I opening a HUB. 

So, I check the changelog and I see than the version 18.7.0 change something with the widget (tweaked refresh widget) so that confirm than the problem come from this version. Finally I go back to the version available on the kodi repo (18.6.25) and the problem are gone ,all works correctly and the widgets refresh automatically when new content are added. 
So I disabled the auto-update for now but if you can take a look on this problem that would be awesome. 

Thank you in advance :)

**Comment by sualfred** [comment]
The tweaked mechanism only applies for real Kodi database items. EmbyCon isn't affected by this at all, because I always used "VideoLibary.onUpdate()" as trigger. Since EmbyCon is not syncing anything to the DB it has nothing to do with it.
And the only "tweaked" mechanism is, that I force widget containers to be visible if they were empty before (on a library update). And this one is set by the script.embuary.helper addon, not be skin that you have downgraded. So it works for you again "by accident".

EmbyCon stuff is handled similar, but the property to force Kodi to reload the widget container is set by the addon and not by me. 

To be sure I just added a movie to Emby and it was shown after ~10s in the widget (Emby for Kodi addon)
